name: flutter_settings_kit
description: "Persisted theme, locale, and app-settings primitives for Flutter, with zero forced dependencies."
version: 0.0.1
homepage: https://github.com/henokcheklie/flutter_settings_kit
repository: https://github.com/henokcheklie/flutter_settings_kit
issue_tracker: https://github.com/henokcheklie/flutter_settings_kit_issue_tracker/issues
license: MIT
license_file: LICENSE

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^10.2.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences_platform_interface: ^2.4.2
  very_good_analysis: ^11.0.0

flutter:
